version: '3.4'

services:
  currencyconversionapi:
    image: currencyconversionapi
    build:
      context: currency-conversion-api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
